/**
 * T050: Gitignore automation for local scope
 *
 * Automatically adds .claude/memory/local/ to .gitignore
 * to keep local memories private.
 */

import { readFile, writeFile, access } from 'node:fs/promises';
import * as path from 'node:path';
import { findGitRoot } from './git-utils.js';
import { createLogger } from '../core/logger.js';

const log = createLogger('gitignore');

/** Pattern to add to .gitignore for local memories */
export const MEMORY_LOCAL_PATTERN = '.claude/memory/local/';

/** Comment to add before the pattern */
const MEMORY_LOCAL_COMMENT = '# Claude Code local memories (personal, not shared)';

/**
 * Result of gitignore operation
 */
export interface GitignoreResult {
  /** Whether .gitignore was created */
  created: boolean;
  /** Whether .gitignore was modified */
  modified: boolean;
  /** Whether pattern was already present */
  alreadyPresent: boolean;
  /** Whether operation was skipped */
  skipped: boolean;
  /** Reason for skipping */
  reason?: string;
}

/**
 * Ensure the local scope directory is gitignored
 *
 * @param projectRoot - Project root directory (or cwd)
 * @returns Result of the operation
 */
export async function ensureLocalScopeGitignored(projectRoot: string): Promise<GitignoreResult> {
  // Find git root
  const gitRoot = await findGitRoot(projectRoot);
  if (!gitRoot) {
    return {
      created: false,
      modified: false,
      alreadyPresent: false,
      skipped: true,
      reason: 'Not a git repository',
    };
  }

  const gitignorePath = path.join(gitRoot, '.gitignore');

  // Check if already present
  if (await isPathGitignored(gitRoot, MEMORY_LOCAL_PATTERN)) {
    return {
      created: false,
      modified: false,
      alreadyPresent: true,
      skipped: false,
    };
  }

  // Create or modify .gitignore
  const created = await createGitignoreIfMissing(gitRoot);
  await addToGitignore(gitRoot, MEMORY_LOCAL_PATTERN, MEMORY_LOCAL_COMMENT);

  log.info('Added local memory path to .gitignore', { path: gitignorePath });

  return {
    created,
    modified: !created,
    alreadyPresent: false,
    skipped: false,
  };
}

/**
 * Check if a pattern is in the .gitignore file
 */
export async function isPathGitignored(gitRoot: string, pattern: string): Promise<boolean> {
  const gitignorePath = path.join(gitRoot, '.gitignore');

  try {
    await access(gitignorePath);
  } catch {
    return false;
  }

  try {
    const content = await readFile(gitignorePath, 'utf-8');
    const lines = content.split(/\r?\n/);

    // Check for exact match (with optional whitespace)
    const normalizedPattern = pattern.trim();
    return lines.some(line => line.trim() === normalizedPattern);
  } catch {
    return false;
  }
}

/**
 * Add a pattern to .gitignore
 *
 * @param gitRoot - Git repository root
 * @param pattern - Pattern to add
 * @param comment - Optional comment to add before the pattern
 */
export async function addToGitignore(
  gitRoot: string,
  pattern: string,
  comment?: string
): Promise<void> {
  const gitignorePath = path.join(gitRoot, '.gitignore');

  let content = '';
  try {
    await access(gitignorePath);
    content = await readFile(gitignorePath, 'utf-8');
  } catch {
    // File does not exist; start with empty content
  }

  // Ensure content ends with newline
  if (content && !content.endsWith('\n')) {
    content += '\n';
  }

  // Add blank line before comment/pattern if content exists
  if (content && content.trim().length > 0 && comment) {
    content += '\n';
  }

  // Add comment if provided (ensure it starts with #)
  if (comment) {
    const commentLine = comment.startsWith('#') ? comment : `# ${comment}`;
    content += commentLine + '\n';
  }

  // Add pattern
  content += pattern + '\n';

  await writeFile(gitignorePath, content);
  log.debug('Added to .gitignore', { pattern });
}

/**
 * Create .gitignore if it doesn't exist
 *
 * @param gitRoot - Git repository root
 * @returns true if created, false if already exists
 */
export async function createGitignoreIfMissing(gitRoot: string): Promise<boolean> {
  const gitignorePath = path.join(gitRoot, '.gitignore');

  try {
    await access(gitignorePath);
    return false;
  } catch {
    // File does not exist; create it
  }

  const initialContent = '# Generated by Claude Code\n\n';
  await writeFile(gitignorePath, initialContent);
  log.debug('Created .gitignore', { path: gitignorePath });

  return true;
}

/**
 * Remove a pattern from .gitignore
 *
 * @param gitRoot - Git repository root
 * @param pattern - Pattern to remove
 * @returns true if removed, false if not found
 */
export async function removeFromGitignore(gitRoot: string, pattern: string): Promise<boolean> {
  const gitignorePath = path.join(gitRoot, '.gitignore');

  try {
    await access(gitignorePath);
  } catch {
    return false;
  }

  const content = await readFile(gitignorePath, 'utf-8');
  const lines = content.split(/\r?\n/);
  const normalizedPattern = pattern.trim();

  const filteredLines = lines.filter(line => line.trim() !== normalizedPattern);

  if (filteredLines.length === lines.length) {
    return false; // Pattern not found
  }

  await writeFile(gitignorePath, filteredLines.join('\n'));
  log.debug('Removed from .gitignore', { pattern });

  return true;
}

/**
 * Check all local memory patterns are gitignored
 */
export async function validateGitignorePatterns(gitRoot: string): Promise<{
  valid: boolean;
  missing: string[];
}> {
  const requiredPatterns = [MEMORY_LOCAL_PATTERN];
  const missing: string[] = [];

  for (const pattern of requiredPatterns) {
    if (!(await isPathGitignored(gitRoot, pattern))) {
      missing.push(pattern);
    }
  }

  return {
    valid: missing.length === 0,
    missing,
  };
}
